In [1]:
import os
import pandas as pd

In [2]:
dti_df = pd.read_csv('data\dti.csv')
dti_df.head()

,subject_id,DIAGNOSIS,dti_date,PTDOBYY,PTGENDER,dti_link
0,002_S_0413,1.0,2017-06-21,1929.0,2.0,data\DTI\002_S_0413\Axial_DTI_FA\2017-06-21_13...
1,002_S_1155,2.0,2017-04-24,1949.0,1.0,data\DTI\002_S_1155\Axial_DTI_FA\2017-04-24_13...
2,002_S_1280,1.0,2017-03-13,1936.0,2.0,data\DTI\002_S_1280\Axial_DTI_FA\2017-03-13_14...
3,002_S_1280,1.0,2017-03-13,1936.0,2.0,data\DTI\002_S_1280\Axial_DTI_FA\2017-03-13_14...
4,002_S_4225,3.0,2018-11-12,1941.0,1.0,data\DTI\002_S_4225\Axial_DTI_FA\2018-11-12_10...

In [3]:
dti_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 163 entries, 0 to 162
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   subject_id  163 non-null    object
 1   DIAGNOSIS   163 non-null    float64
 2   dti_date    163 non-null    object
 3   PTDOBYY     163 non-null    float64
 4   PTGENDER    163 non-null    float64
 5   dti_link    163 non-null    object
dtypes: float64(3), object(3)
memory usage: 7.8+ KB

In [4]:
mri_df = pd.read_csv('data\mri.csv')
mri_df.head()

,subject_id,DIAGNOSIS,mri_date,mri_link
0,002_S_0413,1.0,2017-06-21,data\MRI\002_S_0413\Accelerated_Sagittal_MPRAG...
1,002_S_1155,2.0,2017-04-24,data\MRI\002_S_1155\Accelerated_Sagittal_MPRAG...
2,002_S_1261,2.0,2017-03-15,data\MRI\002_S_1261\Accelerated_Sagittal_MPRAG...
3,002_S_1280,1.0,2017-03-13,data\MRI\002_S_1280\Accelerated_Sagittal_MPRAG...
4,002_S_4225,3.0,2018-11-12,data\MRI\002_S_4225\Accelerated_Sagittal_MPRAG...

In [5]:
mri_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 197 entries, 0 to 196
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   subject_id  197 non-null    object
 1   DIAGNOSIS   197 non-null    float64
 2   mri_date    197 non-null    object
 3   mri_link    197 non-null    object
dtypes: float64(1), object(3)
memory usage: 6.3+ KB

In [6]:
df = pd.merge(dti_df, mri_df, on=['subject_id', 'DIAGNOSIS'], how='inner')
df.head()

,subject_id,DIAGNOSIS,dti_date,PTDOBYY,PTGENDER,dti_link,mri_date,mri_link
0,002_S_0413,1.0,2017-06-21,1929.0,2.0,data\DTI\002_S_0413\Axial_DTI_FA\2017-06-21_13...,2017-06-21,data\MRI\002_S_0413\Accelerated_Sagittal_MPRAG...
1,002_S_1155,2.0,2017-04-24,1949.0,1.0,data\DTI\002_S_1155\Axial_DTI_FA\2017-04-24_13...,2017-04-24,data\MRI\002_S_1155\Accelerated_Sagittal_MPRAG...
2,002_S_1280,1.0,2017-03-13,1936.0,2.0,data\DTI\002_S_1280\Axial_DTI_FA\2017-03-13_14...,2017-03-13,data\MRI\002_S_1280\Accelerated_Sagittal_MPRAG...
3,002_S_1280,1.0,2017-03-13,1936.0,2.0,data\DTI\002_S_1280\Axial_DTI_FA\2017-03-13_14...,2017-03-13,data\MRI\002_S_1280\Accelerated_Sagittal_MPRAG...
4,002_S_4225,3.0,2018-11-12,1941.0,1.0,data\DTI\002_S_4225\Axial_DTI_FA\2018-11-12_10...,2018-11-12,data\MRI\002_S_4225\Accelerated_Sagittal_MPRAG...

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   subject_id  301 non-null    object
 1   DIAGNOSIS   301 non-null    float64
 2   dti_date    301 non-null    object
 3   PTDOBYY     301 non-null    float64
 4   PTGENDER    301 non-null    float64
 5   dti_link    301 non-null    object
 6   mri_date    301 non-null    object
 7   mri_link    301 non-null    object
dtypes: float64(3), object(5)
memory usage: 18.9+ KB

In [8]:
# 1 cột mới ở df là số ngày giữa dti_date và mri_date
df['dti_date'] = pd.to_datetime(df['dti_date'])
df['mri_date'] = pd.to_datetime(df['mri_date'])

df['days_between'] = abs((df['mri_date'] - df['dti_date']).dt.days)
df.head()

,subject_id,DIAGNOSIS,dti_date,PTDOBYY,PTGENDER,dti_link,mri_date,mri_link,days_between
0,002_S_0413,1.0,2017-06-21,1929.0,2.0,data\DTI\002_S_0413\Axial_DTI_FA\2017-06-21_13...,2017-06-21,data\MRI\002_S_0413\Accelerated_Sagittal_MPRAG...,0
1,002_S_1155,2.0,2017-04-24,1949.0,1.0,data\DTI\002_S_1155\Axial_DTI_FA\2017-04-24_13...,2017-04-24,data\MRI\002_S_1155\Accelerated_Sagittal_MPRAG...,0
2,002_S_1280,1.0,2017-03-13,1936.0,2.0,data\DTI\002_S_1280\Axial_DTI_FA\2017-03-13_14...,2017-03-13,data\MRI\002_S_1280\Accelerated_Sagittal_MPRAG...,0
3,002_S_1280,1.0,2017-03-13,1936.0,2.0,data\DTI\002_S_1280\Axial_DTI_FA\2017-03-13_14...,2017-03-13,data\MRI\002_S_1280\Accelerated_Sagittal_MPRAG...,0
4,002_S_4225,3.0,2018-11-12,1941.0,1.0,data\DTI\002_S_4225\Axial_DTI_FA\2018-11-12_10...,2018-11-12,data\MRI\002_S_4225\Accelerated_Sagittal_MPRAG...,0

In [9]:
df['days_between'].unique()

array([   0,  457,  828,  583,  893,  786,  512,  388,  326,  351,  665,
       1689,  314, 1338, 1024,  335,  840,  399,  398,  741, 1698,  343,
       1300,  957,  727,  425,  705,  280,  373,  710, 1666,  337, 1293,
        956,  698,  356,  739,  737, 1659,  922,  928,  918,  875,  336,
        867, 1521,  531, 1185,  654,  507,  428,  925,  497,  429,  974,
        545,  403,  784, 1100,    7], dtype=int64)

In [10]:
df = df[df['days_between'] < 7]
df.head()

,subject_id,DIAGNOSIS,dti_date,PTDOBYY,PTGENDER,dti_link,mri_date,mri_link,days_between
0,002_S_0413,1.0,2017-06-21,1929.0,2.0,data\DTI\002_S_0413\Axial_DTI_FA\2017-06-21_13...,2017-06-21,data\MRI\002_S_0413\Accelerated_Sagittal_MPRAG...,0
1,002_S_1155,2.0,2017-04-24,1949.0,1.0,data\DTI\002_S_1155\Axial_DTI_FA\2017-04-24_13...,2017-04-24,data\MRI\002_S_1155\Accelerated_Sagittal_MPRAG...,0
2,002_S_1280,1.0,2017-03-13,1936.0,2.0,data\DTI\002_S_1280\Axial_DTI_FA\2017-03-13_14...,2017-03-13,data\MRI\002_S_1280\Accelerated_Sagittal_MPRAG...,0
3,002_S_1280,1.0,2017-03-13,1936.0,2.0,data\DTI\002_S_1280\Axial_DTI_FA\2017-03-13_14...,2017-03-13,data\MRI\002_S_1280\Accelerated_Sagittal_MPRAG...,0
4,002_S_4225,3.0,2018-11-12,1941.0,1.0,data\DTI\002_S_4225\Axial_DTI_FA\2018-11-12_10...,2018-11-12,data\MRI\002_S_4225\Accelerated_Sagittal_MPRAG...,0

In [11]:
df['days_between'].unique()

array([0], dtype=int64)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 172 entries, 0 to 300
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   subject_id    172 non-null    object
 1   DIAGNOSIS     172 non-null    float64
 2   dti_date      172 non-null    datetime64[ns]
 3   PTDOBYY       172 non-null    float64
 4   PTGENDER      172 non-null    float64
 5   dti_link      172 non-null    object
 6   mri_date      172 non-null    datetime64[ns]
 7   mri_link      172 non-null    object
 8   days_between  172 non-null    int64
dtypes: datetime64[ns](2), float64(3), int64(1), object(3)
memory usage: 13.4+ KB

In [13]:
# in những dòng bị trùng subject_id

df1 = df[df.duplicated(subset=['dti_link'], keep=False)].sort_values(by='subject_id')

In [14]:
df1

,subject_id,DIAGNOSIS,dti_date,PTDOBYY,PTGENDER,dti_link,mri_date,mri_link,days_between
92,041_S_0679,1.0,2022-02-18,1943.0,1.0,data\DTI\041_S_0679\Axial_DTI_FA\2022-02-18_11...,2022-02-18,data\MRI\041_S_0679\Accelerated_Sagittal_MPRAG...,0
93,041_S_0679,1.0,2022-02-18,1943.0,1.0,data\DTI\041_S_0679\Axial_DTI_FA\2022-02-18_11...,2022-02-18,data\MRI\041_S_0679\Accelerated_Sagittal_MPRAG...,0
94,041_S_1418,2.0,2018-08-23,1926.0,1.0,data\DTI\041_S_1418\Axial_DTI_FA\2018-08-23_10...,2018-08-23,data\MRI\041_S_1418\Accelerated_Sagittal_MPRAG...,0
95,041_S_1418,2.0,2018-08-23,1926.0,1.0,data\DTI\041_S_1418\Axial_DTI_FA\2018-08-23_10...,2018-08-23,data\MRI\041_S_1418\Accelerated_Sagittal_MPRAG...,0
100,041_S_4037,1.0,2017-07-13,1935.0,1.0,data\DTI\041_S_4037\Axial_DTI_FA\2017-07-13_11...,2017-07-13,data\MRI\041_S_4037\Accelerated_Sagittal_MPRAG...,0
101,041_S_4037,1.0,2017-07-13,1935.0,1.0,data\DTI\041_S_4037\Axial_DTI_FA\2017-07-13_11...,2017-07-13,data\MRI\041_S_4037\Accelerated_Sagittal_MPRAG...,0
102,041_S_4051,1.0,2017-07-05,1940.0,1.0,data\DTI\041_S_4051\Axial_DTI_FA\2017-07-05_08...,2017-07-05,data\MRI\041_S_4051\Accelerated_Sagittal_MPRAG...,0
103,041_S_4051,1.0,2017-07-05,1940.0,1.0,data\DTI\041_S_4051\Axial_DTI_FA\2017-07-05_08...,2017-07-05,data\MRI\041_S_4051\Accelerated_Sagittal_MPRAG...,0
110,041_S_4200,1.0,2022-03-31,1941.0,2.0,data\DTI\041_S_4200\Axial_DTI_FA\2022-03-31_11...,2022-03-31,data\MRI\041_S_4200\Accelerated_Sagittal_MPRAG...,0
109,041_S_4200,1.0,2022-03-31,1941.0,2.0,data\DTI\041_S_4200\Axial_DTI_FA\2022-03-31_11...,2022-03-31,data\MRI\041_S_4200\Accelerated_Sagittal_MPRAG...,0
164,041_S_5141,1.0,2017-08-18,1936.0,1.0,data\DTI\041_S_5141\Axial_DTI_FA\2017-08-18_15...,2017-08-18,data\MRI\041_S_5141\Accelerated_Sagittal_MPRAG...,0
165,041_S_5141,1.0,2017-08-18,1936.0,1.0,data\DTI\041_S_5141\Axial_DTI_FA\2017-08-18_15...,2017-08-18,data\MRI\041_S_5141\Accelerated_Sagittal_MPRAG...,0
174,041_S_5253,2.0,2023-03-27,1945.0,1.0,data\DTI\041_S_5253\Axial_DTI_FA\2023-03-27_08...,2023-03-27,data\MRI\041_S_5253\Accelerated_Sagittal_MPRAG...,0
175,041_S_5253,2.0,2023-03-27,1945.0,1.0,data\DTI\041_S_5253\Axial_DTI_FA\2023-03-27_08...,2023-03-27,data\MRI\041_S_5253\Accelerated_Sagittal_MPRAG...,0
181,041_S_6192,1.0,2018-01-31,1934.0,2.0,data\DTI\041_S_6192\Axial_DTI_FA\2018-01-31_08...,2018-01-31,data\MRI\041_S_6192\Accelerated_Sagittal_MPRAG...,0
182,041_S_6192,1.0,2018-01-31,1934.0,2.0,data\DTI\041_S_6192\Axial_DTI_FA\2018-01-31_08...,2018-01-31,data\MRI\041_S_6192\Accelerated_Sagittal_MPRAG...,0
246,041_S_6786,1.0,2022-04-27,1932.0,2.0,data\DTI\041_S_6786\Axial_DTI_FA\2022-04-27_10...,2022-04-27,data\MRI\041_S_6786\Accelerated_Sagittal_MPRAG...,0
247,041_S_6786,1.0,2022-04-27,1932.0,2.0,data\DTI\041_S_6786\Axial_DTI_FA\2022-04-27_10...,2022-04-27,data\MRI\041_S_6786\Accelerated_Sagittal_MPRAG...,0

In [15]:
df1.iloc[0]['mri_link']

'data\\MRI\\041_S_0679\\Accelerated_Sagittal_MPRAGE\\2022-02-18_10_41_49.0\\I1555329'

In [16]:
df1.iloc[1]['mri_link']

'data\\MRI\\041_S_0679\\Accelerated_Sagittal_MPRAGE\\2022-02-18_10_41_49.0\\I1555330'

In [17]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18 entries, 92 to 247
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   subject_id    18 non-null     object
 1   DIAGNOSIS     18 non-null     float64
 2   dti_date      18 non-null     datetime64[ns]
 3   PTDOBYY       18 non-null     float64
 4   PTGENDER      18 non-null     float64
 5   dti_link      18 non-null     object
 6   mri_date      18 non-null     datetime64[ns]
 7   mri_link      18 non-null     object
 8   days_between  18 non-null     int64
dtypes: datetime64[ns](2), float64(3), int64(1), object(3)
memory usage: 1.4+ KB

In [18]:
# xóa cột khong cần thiết
df = df.drop(columns=['dti_date', 'mri_date', 'days_between', 'subject_id'])

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 172 entries, 0 to 300
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   DIAGNOSIS  172 non-null    float64
 1   PTDOBYY    172 non-null    float64
 2   PTGENDER   172 non-null    float64
 3   dti_link   172 non-null    object
 4   mri_link   172 non-null    object
dtypes: float64(3), object(2)
memory usage: 8.1+ KB

In [22]:
df.head()

,DIAGNOSIS,PTDOBYY,PTGENDER,dti_link,mri_link
0,1.0,1929.0,2.0,data\DTI\002_S_0413\Axial_DTI_FA\2017-06-21_13...,data\MRI\002_S_0413\Accelerated_Sagittal_MPRAG...
1,2.0,1949.0,1.0,data\DTI\002_S_1155\Axial_DTI_FA\2017-04-24_13...,data\MRI\002_S_1155\Accelerated_Sagittal_MPRAG...
2,1.0,1936.0,2.0,data\DTI\002_S_1280\Axial_DTI_FA\2017-03-13_14...,data\MRI\002_S_1280\Accelerated_Sagittal_MPRAG...
3,1.0,1936.0,2.0,data\DTI\002_S_1280\Axial_DTI_FA\2017-03-13_14...,data\MRI\002_S_1280\Accelerated_Sagittal_MPRAG...
4,3.0,1941.0,1.0,data\DTI\002_S_4225\Axial_DTI_FA\2018-11-12_10...,data\MRI\002_S_4225\Accelerated_Sagittal_MPRAG...

In [20]:
df.DIAGNOSIS.value_counts()

DIAGNOSIS
1.0    111
2.0     41
3.0     20
Name: count, dtype: int64

In [21]:
# lưu:
df.to_csv('data/final.csv', index=False)